echo \
"EXPLORER_PORT=${EXPLORER_PORT:-3000}
EXPLORER_NETWORK_ENV=${EXPLORER_NETWORK_ENV:-testnet}
EXPLORER_MONGODB_URL=${EXPLORER_MONGODB_URL:${EXPLORER_MONGODB_URL:-mongodb://127.0.0.1:27017/app}
EXPLORER_SENTRY_DSN=${EXPLORER_SENTRY_DSN}
EXPLORER_ALCHEMY_GOERLI_RPC=''" \
> .env

echo "Env files successfully generated."
